[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name         = "advent-of-code"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13.0"
numpy  = "^2.1.0"
